name: Terraform Workflow

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

      # Replace with your desired Terraform version something

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS credentials
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}" >> $GITHUB_ENV

    - name: Initialize Terraform
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply  --auto-approve

    - name: Setup Kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

    - name: Install Helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod +x get_helm.sh
        ./get_helm.sh

    - name: Add Helm Repository
      run: |
        helm repo add stable https://charts.helm.sh/stable

    - name: Deploy Helm Chart
      run: |
        helm upgrade --install my-release stable/my-chart --namespace my-namespace
